version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - ./deployment.sh -b
  pre_build:
    commands:
      - ./deployment.sh -p
  build:
    commands:
      - ./deployment.sh -d
  post_build:
    commands:
      - echo post-build